# Generated by Django 4.2 on 2026-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SECURITY', 'Security'), ('HOST', 'Host')], default='HOST', max_length=20),
        ),
    ]
