# Generated by Django 4.2 on 2026-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='expected_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('VENDOR', 'Vendor'), ('INTERVIEW', 'Interview'), ('DELIVERY', 'Delivery')], max_length=20, null=True),
        ),
    ]
